export const EXAMPLE_RAW_PDF_1: string[] = [
  "Paseo de Antonio Machado, 12 29002 Málaga TLF 951.926 067 www.malaga.eu",
  "Área Juventud",
  "Buceo en el Peñón del Cuervo",
  "Descripción de la",
  "Actividad",
  "Te proponemos un plan que no podrás resistir...., una actividad de",
  "iniciación al buceo en la que aprenderás a realizar inmersiones con todo el",
  "material profesional necesario para que sea inolvidable y disfrutes de esta",
  "increíble experiencia de manera segura. Seguro que la actividad te va a",
  "gustar tanto que vas a querer quedarte más tiempo buceando.",
  "Cuando consigas tu plaza es imprescindible que prestes atención a tu correo electrónico, ya que",
  "se te enviará un cuestionario pidiéndote los siguientes datos personales: talla de pie, altura, peso",
  "y tu dni para asegurarte que el equipo que te llevan te estará bien. No se admitirá ninguna",
  "información del equipo posterior a las 13:30h del jueves 18/07/24.",
  "¡ATENCIÓN!, en esta actividad sólo podrás participar una vez este año y si no tienes ningún título oficial de",
  "buceo (excluido el de bautismo de buceo), en el caso de conseguir plaza te daremos de baja para que otras",
  "personas puedan disfrutar de esta actividad.",
  "Fecha Inscripción: Realización:",
  "Del 17 al 18 de julio Viernes 19 de julio de 2024",
  "Información",
  "Básica",
  "Tres turnos de 10 plazas cada uno",
  "Hora de inicio Turno Primero: 9:00h Hora finalización: 10:30h (aproximadamente)",
  "Hora de inicio Turno Segundo: 10:30h Hora finalización: 12:00h (aproximadamente)",
  "Hora de inicio Turno Segundo: 12:00h Hora finalización: 13:30 (aproximadamente)",
  "Lugar de realización: Playa del Peñón del Cuervo https://g.co/kgs/Jheewvb",
  "¿Qué haremos?",
  "- Recepción y presentación del grupo y monitores.",
  "- Charla previa en superficie, ajuste del material de inmersión.",
  "- Inmersión en el mar de unos cuarenta minutos.",
  "- Valoración de la actividad.",
  "Ten en cuenta....",
  "Te recomendamos que lleves protector solar y algo ligero para picar.",
  "Es imprescindible que asistas con ropa de baño.",
  "Requisitos para",
  "participar",
  "El programa Alterna en tu Ocio está sujeto a una política de Sanciones recogida en la Normativa",
  "de Participación que puedes consultar www.juventud.malaga.eu",
  "Es imprescindible estar registrado en la Base de Datos de Juventud para poder participar en el",
  "programa, así como tener entre 15 y 35 años. Los menores de edad tendrán que presentar la",
  "autorización de uno de sus tutores legales junto a la fotocopia del documento acreditativo (DNI,",
  "pasaporte) antes del inicio de la actividad.",
  "Esta actividad no dispone de inscripciones “in-situ”.",
  "Antes de comenzar la actividad tendrás que presentar obligatoriamente el D.N.I. (o cualquier",
  "otro documento oficial equivalente)",
  "Si necesitas más",
  "información",
  "Puedes contactar con Más Animación: aeto@masanimacion.com",
];

export const EXAMPLE_RAW_PDF_2: string[] = [
  "Paseo de Antonio Machado, 12 29002 Málaga TLF 951.926 067 www.malaga.eu",
  "Área Juventud",
  "Juegos de Mesa",
  "Descripción de la",
  "Actividad",
  "¿Te apetece pasar unas horas divertidas? Pues no lo dudes, esta actividad está pensada",
  "para ti, te proponemos que pases unas horas divertidas descubriendo un gran número de",
  "juegos de diferentes tipos para que descubras cuál te gusta más.",
  "En esta actividad no sólo vas a descubrir el extenso mundo de los juegos de mesa, probar",
  "las últimas novedades, divertirte y conocer a más gente, sino que además participarás",
  "en el sorteo de unos juegos de mesa, no puedes perdértelo, ¡consigue tu plaza y",
  "demuestra tus habilidades!",
  "Fecha",
  "Inscripción: Realización:",
  "Del 7 al 9 de marzo Sábado 9 de marzo de 2024",
  "Información",
  "Básica",
  "Un único turno de 20 plazas",
  "Hora de inicio: 22h Hora finalización: 1h (aproximadamente)",
  "Lugar de realización: Instalaciones de La Máquina Imaginaria – Centro Comercial Málaga Ocio. Local 2, planta",
  "baja (tras escaleras mecánicas) https://maps.app.goo.gl/K6A7EtMVAy9Rohka7",
  "¿Qué haremos?",
  "- Recepción y presentación de los participantes y monitores.",
  "- División de los participantes en grupos para probar los diferentes juegos.",
  "- Se sorteará un juego de mesa entre los asistentes.",
  "- Valoración de la actividad.",
  "Ten en cuenta....",
  "Se recomienda asistir con ropa y calzado cómodo.",
  "Requisitos para",
  "participar",
  "El programa Alterna en tu Ocio está sujeto a una política de Sanciones recogida en la Normativa de",
  "Participación que puedes consultar www.juventud.malaga.eu",
  "Es imprescindible estar registrado en la Base de Datos de Juventud para poder participar en el programa, así",
  "como tener entre 15 y 35 años. Los menores de edad tendrán que presentar la autorización de uno de sus",
  "tutores legales junto a la fotocopia del documento acreditativo (DNI, pasaporte) antes del inicio de la",
  "actividad.",
  "Podrás participar en la actividad hasta un máximo de cinco minutos pasada la hora prevista de inicio, por lo",
  "que se recomienda llegar al lugar de ejecución unos minutos antes del inicio de la actividad. Pasado ese",
  "tiempo, la plaza quedará libre a disposición de otros usuarios interesados, sin derecho a ninguna",
  "reclamación.",
  "Antes de comenzar la actividad tendrás que presentar obligatoriamente el D.N.I. (o cualquier otro",
  "documento oficial equivalente)",
  "Si necesitas más",
  "información",
  "Puedes contactar con Más Animación: aeto@masanimacion.com",
];
